CREATE TABLE LIBRARY
(
    ID                          TEXT      NOT NULL PRIMARY KEY,
    CREATED_DATE                TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE          TIMESTAMP NOT NULL DEFAULT NOW(),
    NAME                        TEXT      NOT NULL,
    ROOT                        TEXT      NOT NULL,
    IMPORT_COMICINFO_BOOK       BOOLEAN   NOT NULL DEFAULT TRUE,
    IMPORT_COMICINFO_SERIES     BOOLEAN   NOT NULL DEFAULT TRUE,
    IMPORT_COMICINFO_COLLECTION BOOLEAN   NOT NULL DEFAULT TRUE,
    IMPORT_EPUB_BOOK            BOOLEAN   NOT NULL DEFAULT TRUE,
    IMPORT_EPUB_SERIES          BOOLEAN   NOT NULL DEFAULT TRUE,
    SCAN_FORCE_MODIFIED_TIME    BOOLEAN   NOT NULL DEFAULT FALSE,
    SCAN_STARTUP                BOOLEAN   NOT NULL DEFAULT FALSE,
    IMPORT_LOCAL_ARTWORK        BOOLEAN   NOT NULL DEFAULT TRUE,
    IMPORT_COMICINFO_READLIST   BOOLEAN   NOT NULL DEFAULT TRUE,
    IMPORT_BARCODE_ISBN         BOOLEAN   NOT NULL DEFAULT TRUE,
    CONVERT_TO_CBZ              BOOLEAN   NOT NULL DEFAULT FALSE,
    REPAIR_EXTENSIONS           BOOLEAN   NOT NULL DEFAULT FALSE,
    EMPTY_TRASH_AFTER_SCAN      BOOLEAN   NOT NULL DEFAULT FALSE,
    IMPORT_MYLAR_SERIES         BOOLEAN   NOT NULL DEFAULT TRUE,
    SERIES_COVER                TEXT      NOT NULL DEFAULT 'FIRST',
    UNAVAILABLE_DATE            TIMESTAMP NULL     DEFAULT NULL,
    HASH_FILES                  BOOLEAN   NOT NULL DEFAULT TRUE,
    HASH_PAGES                  BOOLEAN   NOT NULL DEFAULT FALSE,
    ANALYZE_DIMENSIONS          BOOLEAN   NOT NULL DEFAULT TRUE,
    IMPORT_COMICINFO_SERIES_APPEND_VOLUME BOOLEAN NOT NULL DEFAULT TRUE,
    ONESHOTS_DIRECTORY          TEXT      NULL     DEFAULT NULL,
    SCAN_CBX                    BOOLEAN   NOT NULL DEFAULT TRUE,
    SCAN_PDF                    BOOLEAN   NOT NULL DEFAULT TRUE,
    SCAN_EPUB                   BOOLEAN   NOT NULL DEFAULT TRUE,
    SCAN_INTERVAL               TEXT      NOT NULL DEFAULT 'EVERY_6H',
    HASH_KOREADER               BOOLEAN   NOT NULL DEFAULT FALSE
);

CREATE TABLE "USER"
(
    ID                         TEXT      NOT NULL PRIMARY KEY,
    CREATED_DATE               TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE         TIMESTAMP NOT NULL DEFAULT NOW(),
    EMAIL                      TEXT      NOT NULL UNIQUE,
    PASSWORD                   TEXT      NOT NULL,
    SHARED_ALL_LIBRARIES       BOOLEAN   NOT NULL DEFAULT TRUE,
    AGE_RESTRICTION            INTEGER   NULL,
    AGE_RESTRICTION_ALLOW_ONLY BOOLEAN   NULL
);

CREATE TABLE USER_ROLE
(
    USER_ID TEXT NOT NULL,
    ROLE    TEXT NOT NULL,
    PRIMARY KEY (USER_ID, ROLE),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE USER_LIBRARY_SHARING
(
    USER_ID    TEXT NOT NULL,
    LIBRARY_ID TEXT NOT NULL,
    PRIMARY KEY (USER_ID, LIBRARY_ID),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID),
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID)
);

CREATE TABLE SERIES
(
    ID                 TEXT      NOT NULL PRIMARY KEY,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    FILE_LAST_MODIFIED TIMESTAMP NOT NULL,
    NAME               TEXT      NOT NULL,
    URL                TEXT      NOT NULL,
    LIBRARY_ID         TEXT      NOT NULL,
    BOOK_COUNT         INTEGER   NOT NULL DEFAULT 0,
    DELETED_DATE       TIMESTAMP NULL     DEFAULT NULL,
    ONESHOT            BOOLEAN   NOT NULL DEFAULT FALSE,
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID)
);

CREATE TABLE SERIES_METADATA
(
    CREATED_DATE                          TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE                    TIMESTAMP NOT NULL DEFAULT NOW(),
    STATUS                                TEXT      NOT NULL,
    STATUS_LOCK                           BOOLEAN   NOT NULL DEFAULT FALSE,
    TITLE                                 TEXT      NOT NULL,
    TITLE_LOCK                            BOOLEAN   NOT NULL DEFAULT FALSE,
    TITLE_SORT                            TEXT      NOT NULL,
    TITLE_SORT_LOCK                       BOOLEAN   NOT NULL DEFAULT FALSE,
    SERIES_ID                             TEXT      NOT NULL PRIMARY KEY,
    PUBLISHER                             TEXT      NOT NULL DEFAULT '',
    PUBLISHER_LOCK                        BOOLEAN   NOT NULL DEFAULT FALSE,
    READING_DIRECTION                     TEXT      NULL,
    READING_DIRECTION_LOCK                BOOLEAN   NOT NULL DEFAULT FALSE,
    AGE_RATING                            INTEGER   NULL,
    AGE_RATING_LOCK                       BOOLEAN   NOT NULL DEFAULT FALSE,
    SUMMARY                               TEXT      NOT NULL DEFAULT '',
    SUMMARY_LOCK                          BOOLEAN   NOT NULL DEFAULT FALSE,
    LANGUAGE                              TEXT      NOT NULL DEFAULT '',
    LANGUAGE_LOCK                         BOOLEAN   NOT NULL DEFAULT FALSE,
    GENRES_LOCK                           BOOLEAN   NOT NULL DEFAULT FALSE,
    TAGS_LOCK                             BOOLEAN   NOT NULL DEFAULT FALSE,
    TOTAL_BOOK_COUNT                      INTEGER   NULL,
    TOTAL_BOOK_COUNT_LOCK                 BOOLEAN   NOT NULL DEFAULT FALSE,
    SHARING_LABELS_LOCK                   BOOLEAN   NOT NULL DEFAULT FALSE,
    LINKS_LOCK                            BOOLEAN   NOT NULL DEFAULT FALSE,
    ALTERNATE_TITLES_LOCK                 BOOLEAN   NOT NULL DEFAULT FALSE,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE BOOK
(
    ID                 TEXT      NOT NULL PRIMARY KEY,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    FILE_LAST_MODIFIED TIMESTAMP NOT NULL,
    NAME               TEXT      NOT NULL,
    URL                TEXT      NOT NULL,
    SERIES_ID          TEXT      NOT NULL,
    FILE_SIZE          BIGINT    NOT NULL DEFAULT 0,
    NUMBER             INTEGER   NOT NULL DEFAULT 0,
    LIBRARY_ID         TEXT      NOT NULL,
    FILE_HASH          TEXT      NOT NULL DEFAULT '',
    DELETED_DATE       TIMESTAMP NULL     DEFAULT NULL,
    ONESHOT            BOOLEAN   NOT NULL DEFAULT FALSE,
    FILE_HASH_KOREADER TEXT      NOT NULL DEFAULT '',
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID),
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE MEDIA_PAGE
(
    FILE_NAME  TEXT    NOT NULL,
    MEDIA_TYPE TEXT    NOT NULL,
    NUMBER     INTEGER NOT NULL,
    BOOK_ID    TEXT    NOT NULL,
    WIDTH      INTEGER NULL,
    HEIGHT     INTEGER NULL,
    FILE_HASH  TEXT    NOT NULL DEFAULT '',
    FILE_SIZE  BIGINT  NULL,
    PRIMARY KEY (BOOK_ID, NUMBER),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);

CREATE TABLE MEDIA_FILE
(
    FILE_NAME  TEXT   NOT NULL,
    BOOK_ID    TEXT   NOT NULL,
    MEDIA_TYPE TEXT   NULL,
    SUB_TYPE   TEXT   NULL,
    FILE_SIZE  BIGINT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);

CREATE TABLE BOOK_METADATA_AUTHOR
(
    NAME    TEXT NOT NULL,
    ROLE    TEXT NOT NULL,
    BOOK_ID TEXT NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);

CREATE TABLE COLLECTION
(
    ID                 TEXT      NOT NULL PRIMARY KEY,
    NAME               TEXT      NOT NULL,
    ORDERED            BOOLEAN   NOT NULL DEFAULT FALSE,
    SERIES_COUNT       INTEGER   NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE COLLECTION_SERIES
(
    COLLECTION_ID TEXT    NOT NULL,
    SERIES_ID     TEXT    NOT NULL,
    NUMBER        INTEGER NOT NULL,
    PRIMARY KEY (COLLECTION_ID, SERIES_ID),
    FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION (ID),
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE THUMBNAIL_BOOK
(
    ID                 TEXT      NOT NULL PRIMARY KEY,
    THUMBNAIL          BYTEA     NULL,
    URL                TEXT      NULL,
    SELECTED           BOOLEAN   NOT NULL DEFAULT FALSE,
    TYPE               TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    BOOK_ID            TEXT      NOT NULL,
    WIDTH              INTEGER   NOT NULL DEFAULT 0,
    HEIGHT             INTEGER   NOT NULL DEFAULT 0,
    MEDIA_TYPE         TEXT      NOT NULL DEFAULT '',
    FILE_SIZE          BIGINT    NOT NULL DEFAULT 0,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);

CREATE TABLE MEDIA
(
    MEDIA_TYPE           TEXT      NULL,
    STATUS               TEXT      NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE   TIMESTAMP NOT NULL DEFAULT NOW(),
    COMMENT              TEXT      NULL,
    BOOK_ID              TEXT      NOT NULL PRIMARY KEY,
    PAGE_COUNT           INTEGER   NOT NULL DEFAULT 0,
    EXTENSION_CLASS      TEXT      NULL,
    _UNUSED              TEXT      NULL,
    EXTENSION_VALUE_BLOB BYTEA     NULL,
    EPUB_DIVINA_COMPATIBLE BOOLEAN NOT NULL DEFAULT FALSE,
    EPUB_IS_KEPUB        BOOLEAN   NOT NULL DEFAULT FALSE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);

CREATE TABLE READLIST
(
    ID                 TEXT      NOT NULL PRIMARY KEY,
    NAME               TEXT      NOT NULL,
    BOOK_COUNT         INTEGER   NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    SUMMARY            TEXT      NOT NULL DEFAULT '',
    ORDERED            BOOLEAN   NOT NULL DEFAULT TRUE
);

CREATE TABLE READLIST_BOOK
(
    READLIST_ID TEXT    NOT NULL,
    BOOK_ID     TEXT    NOT NULL,
    NUMBER      INTEGER NOT NULL,
    PRIMARY KEY (READLIST_ID, BOOK_ID),
    FOREIGN KEY (READLIST_ID) REFERENCES READLIST (ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);

CREATE TABLE SERIES_METADATA_GENRE
(
    GENRE     TEXT NOT NULL,
    SERIES_ID TEXT NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE SERIES_METADATA_TAG
(
    TAG       TEXT NOT NULL,
    SERIES_ID TEXT NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE BOOK_METADATA_TAG
(
    TAG     TEXT NOT NULL,
    BOOK_ID TEXT NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);

CREATE TABLE BOOK_METADATA
(
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    NUMBER             TEXT      NOT NULL,
    NUMBER_LOCK        BOOLEAN   NOT NULL DEFAULT FALSE,
    NUMBER_SORT        REAL      NOT NULL,
    NUMBER_SORT_LOCK   BOOLEAN   NOT NULL DEFAULT FALSE,
    RELEASE_DATE       DATE      NULL,
    RELEASE_DATE_LOCK  BOOLEAN   NOT NULL DEFAULT FALSE,
    SUMMARY            TEXT      NOT NULL DEFAULT '',
    SUMMARY_LOCK       BOOLEAN   NOT NULL DEFAULT FALSE,
    TITLE              TEXT      NOT NULL,
    TITLE_LOCK         BOOLEAN   NOT NULL DEFAULT FALSE,
    AUTHORS_LOCK       BOOLEAN   NOT NULL DEFAULT FALSE,
    TAGS_LOCK          BOOLEAN   NOT NULL DEFAULT FALSE,
    BOOK_ID            TEXT      NOT NULL PRIMARY KEY,
    ISBN               TEXT      NOT NULL DEFAULT '',
    ISBN_LOCK          BOOLEAN   NOT NULL DEFAULT FALSE,
    LINKS_LOCK         BOOLEAN   NOT NULL DEFAULT FALSE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);

CREATE TABLE BOOK_METADATA_AGGREGATION
(
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    RELEASE_DATE       DATE      NULL,
    SUMMARY            TEXT      NOT NULL DEFAULT '',
    SUMMARY_NUMBER     TEXT      NOT NULL DEFAULT '',
    SERIES_ID          TEXT      NOT NULL PRIMARY KEY,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE BOOK_METADATA_AGGREGATION_AUTHOR
(
    NAME      TEXT NOT NULL,
    ROLE      TEXT NOT NULL,
    SERIES_ID TEXT NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE READ_PROGRESS_SERIES
(
    SERIES_ID             TEXT      NOT NULL,
    USER_ID               TEXT      NOT NULL,
    READ_COUNT            INTEGER   NOT NULL,
    IN_PROGRESS_COUNT     INTEGER   NOT NULL,
    MOST_RECENT_READ_DATE TIMESTAMP NULL,
    LAST_MODIFIED_DATE    TIMESTAMP NULL,
    PRIMARY KEY (SERIES_ID, USER_ID),
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE SIDECAR
(
    URL                TEXT      NOT NULL PRIMARY KEY,
    PARENT_URL         TEXT      NOT NULL,
    LAST_MODIFIED_TIME TIMESTAMP NOT NULL,
    LIBRARY_ID         TEXT      NOT NULL
);

CREATE TABLE AUTHENTICATION_ACTIVITY
(
    USER_ID         TEXT      NULL     DEFAULT NULL,
    EMAIL           TEXT      NULL     DEFAULT NULL,
    IP              TEXT      NULL     DEFAULT NULL,
    USER_AGENT      TEXT      NULL     DEFAULT NULL,
    SUCCESS         BOOLEAN   NOT NULL,
    ERROR           TEXT      NULL     DEFAULT NULL,
    DATE_TIME       TIMESTAMP NOT NULL DEFAULT NOW(),
    SOURCE          TEXT      NULL     DEFAULT NULL,
    API_KEY_ID      TEXT      NULL     DEFAULT NULL,
    API_KEY_COMMENT TEXT      NULL     DEFAULT NULL,
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE BOOK_METADATA_AGGREGATION_TAG
(
    TAG       TEXT NOT NULL,
    SERIES_ID TEXT NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE THUMBNAIL_SERIES
(
    ID                 TEXT      NOT NULL PRIMARY KEY,
    URL                TEXT      NULL     DEFAULT NULL,
    SELECTED           BOOLEAN   NOT NULL DEFAULT FALSE,
    THUMBNAIL          BYTEA     NULL     DEFAULT NULL,
    TYPE               TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    SERIES_ID          TEXT      NOT NULL,
    WIDTH              INTEGER   NOT NULL DEFAULT 0,
    HEIGHT             INTEGER   NOT NULL DEFAULT 0,
    MEDIA_TYPE         TEXT      NOT NULL DEFAULT '',
    FILE_SIZE          BIGINT    NOT NULL DEFAULT 0,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE READ_PROGRESS
(
    BOOK_ID            TEXT      NOT NULL,
    USER_ID            TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    PAGE               INTEGER   NOT NULL,
    COMPLETED          BOOLEAN   NOT NULL,
    READ_DATE          TIMESTAMP NULL     DEFAULT NOW(),
    DEVICE_ID          TEXT      DEFAULT '',
    DEVICE_NAME        TEXT      DEFAULT '',
    LOCATOR            BYTEA     NULL,
    PRIMARY KEY (BOOK_ID, USER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE TEMP_STRING_LIST
(
    STRING TEXT NOT NULL
);

CREATE TABLE THUMBNAIL_COLLECTION
(
    ID                 TEXT      NOT NULL PRIMARY KEY,
    SELECTED           BOOLEAN   NOT NULL DEFAULT FALSE,
    THUMBNAIL          BYTEA     NOT NULL,
    TYPE               TEXT      NOT NULL,
    COLLECTION_ID      TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    WIDTH              INTEGER   NOT NULL DEFAULT 0,
    HEIGHT             INTEGER   NOT NULL DEFAULT 0,
    MEDIA_TYPE         TEXT      NOT NULL DEFAULT '',
    FILE_SIZE          BIGINT    NOT NULL DEFAULT 0,
    FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION (ID)
);

CREATE TABLE THUMBNAIL_READLIST
(
    ID                 TEXT      NOT NULL PRIMARY KEY,
    SELECTED           BOOLEAN   NOT NULL DEFAULT FALSE,
    THUMBNAIL          BYTEA     NOT NULL,
    TYPE               TEXT      NOT NULL,
    READLIST_ID        TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    WIDTH              INTEGER   NOT NULL DEFAULT 0,
    HEIGHT             INTEGER   NOT NULL DEFAULT 0,
    MEDIA_TYPE         TEXT      NOT NULL DEFAULT '',
    FILE_SIZE          BIGINT    NOT NULL DEFAULT 0,
    FOREIGN KEY (READLIST_ID) REFERENCES READLIST (ID)
);

CREATE TABLE BOOK_METADATA_LINK
(
    LABEL   TEXT NOT NULL,
    URL     TEXT NOT NULL,
    BOOK_ID TEXT NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)
);

CREATE TABLE HISTORICAL_EVENT
(
    ID        TEXT      PRIMARY KEY,
    TYPE      TEXT      NOT NULL,
    BOOK_ID   TEXT      NULL,
    SERIES_ID TEXT      NULL,
    TIMESTAMP TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE HISTORICAL_EVENT_PROPERTIES
(
    ID    TEXT NOT NULL,
    KEY   TEXT NOT NULL,
    VALUE TEXT NOT NULL,
    PRIMARY KEY (ID, KEY),
    FOREIGN KEY (ID) REFERENCES HISTORICAL_EVENT (ID)
);

CREATE TABLE SERIES_METADATA_SHARING
(
    LABEL     TEXT NOT NULL,
    SERIES_ID TEXT NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE USER_SHARING
(
    LABEL   TEXT    NOT NULL,
    ALLOW   BOOLEAN NOT NULL,
    USER_ID TEXT    NOT NULL,
    PRIMARY KEY (LABEL, ALLOW, USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE SERIES_METADATA_LINK
(
    LABEL     TEXT NOT NULL,
    URL       TEXT NOT NULL,
    SERIES_ID TEXT NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE SERIES_METADATA_ALTERNATE_TITLE
(
    LABEL     TEXT NOT NULL,
    TITLE     TEXT NOT NULL,
    SERIES_ID TEXT NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

CREATE TABLE PAGE_HASH
(
    HASH               TEXT      NOT NULL PRIMARY KEY,
    SIZE               BIGINT    NULL,
    ACTION             TEXT      NOT NULL,
    DELETE_COUNT       INTEGER   NOT NULL DEFAULT 0,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE PAGE_HASH_THUMBNAIL
(
    HASH      TEXT  NOT NULL PRIMARY KEY,
    THUMBNAIL BYTEA NOT NULL
);

CREATE TABLE ANNOUNCEMENTS_READ
(
    USER_ID         TEXT NOT NULL,
    ANNOUNCEMENT_ID TEXT NOT NULL,
    PRIMARY KEY (USER_ID, ANNOUNCEMENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE LIBRARY_EXCLUSIONS
(
    LIBRARY_ID TEXT NOT NULL,
    EXCLUSION  TEXT NOT NULL,
    PRIMARY KEY (LIBRARY_ID, EXCLUSION),
    FOREIGN KEY (LIBRARY_ID) REFERENCES LIBRARY (ID)
);

CREATE TABLE SERVER_SETTINGS
(
    KEY   TEXT NOT NULL PRIMARY KEY,
    VALUE TEXT NULL
);

CREATE TABLE USER_API_KEY
(
    ID                 TEXT      NOT NULL PRIMARY KEY,
    USER_ID            TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL DEFAULT NOW(),
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    API_KEY            TEXT      NOT NULL UNIQUE,
    COMMENT            TEXT      NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE SYNC_POINT
(
    ID           TEXT      NOT NULL PRIMARY KEY,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
    USER_ID      TEXT      NOT NULL,
    API_KEY_ID   TEXT      NULL,
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE SYNC_POINT_BOOK_REMOVED_SYNCED
(
    SYNC_POINT_ID TEXT NOT NULL,
    BOOK_ID       TEXT NOT NULL,
    PRIMARY KEY (SYNC_POINT_ID, BOOK_ID),
    FOREIGN KEY (SYNC_POINT_ID) REFERENCES SYNC_POINT (ID)
);

CREATE TABLE SYNC_POINT_BOOK
(
    SYNC_POINT_ID                         TEXT      NOT NULL,
    BOOK_ID                               TEXT      NOT NULL,
    BOOK_CREATED_DATE                     TIMESTAMP NOT NULL,
    BOOK_LAST_MODIFIED_DATE               TIMESTAMP NOT NULL,
    BOOK_FILE_LAST_MODIFIED               TIMESTAMP NOT NULL,
    BOOK_FILE_SIZE                        BIGINT    NOT NULL,
    BOOK_FILE_HASH                        TEXT      NOT NULL,
    BOOK_METADATA_LAST_MODIFIED_DATE      TIMESTAMP NOT NULL,
    BOOK_READ_PROGRESS_LAST_MODIFIED_DATE TIMESTAMP NULL,
    SYNCED                                BOOLEAN   NOT NULL DEFAULT FALSE,
    BOOK_THUMBNAIL_ID                     TEXT      NULL,
    PRIMARY KEY (SYNC_POINT_ID, BOOK_ID),
    FOREIGN KEY (SYNC_POINT_ID) REFERENCES SYNC_POINT (ID)
);

CREATE TABLE SYNC_POINT_READLIST
(
    SYNC_POINT_ID               TEXT      NOT NULL,
    READLIST_ID                 TEXT      NOT NULL,
    READLIST_NAME               TEXT      NOT NULL,
    READLIST_CREATED_DATE       TIMESTAMP NOT NULL,
    READLIST_LAST_MODIFIED_DATE TIMESTAMP NOT NULL,
    SYNCED                      BOOLEAN   NOT NULL DEFAULT FALSE,
    PRIMARY KEY (SYNC_POINT_ID, READLIST_ID),
    FOREIGN KEY (SYNC_POINT_ID) REFERENCES SYNC_POINT (ID)
);

CREATE TABLE SYNC_POINT_READLIST_BOOK
(
    SYNC_POINT_ID TEXT NOT NULL,
    READLIST_ID   TEXT NOT NULL,
    BOOK_ID       TEXT NOT NULL,
    PRIMARY KEY (SYNC_POINT_ID, READLIST_ID, BOOK_ID),
    FOREIGN KEY (SYNC_POINT_ID) REFERENCES SYNC_POINT (ID)
);

CREATE TABLE SYNC_POINT_READLIST_REMOVED_SYNCED
(
    SYNC_POINT_ID TEXT NOT NULL,
    READLIST_ID   TEXT NOT NULL,
    PRIMARY KEY (SYNC_POINT_ID, READLIST_ID),
    FOREIGN KEY (SYNC_POINT_ID) REFERENCES SYNC_POINT (ID)
);

CREATE TABLE BookThumbnail (
    bookId          TEXT NOT NULL PRIMARY KEY,
    seriesId        TEXT NOT NULL,
    thumbnailId     TEXT,
    mediaServer     TEXT NOT NULL
);

CREATE TABLE SeriesThumbnail (
    seriesId        TEXT NOT NULL PRIMARY KEY,
    thumbnailId     TEXT,
    mediaServer     TEXT NOT NULL
);

CREATE TABLE SeriesMatch (
    seriesId            TEXT NOT NULL,
    type                TEXT NOT NULL,
    mediaServer         TEXT NOT NULL,
    provider            TEXT NOT NULL,
    providerSeriesId    TEXT NOT NULL,
    PRIMARY KEY (seriesId, mediaServer)
);

CREATE TABLE KomfJobRecord (
    id          TEXT    NOT NULL,
    seriesId    TEXT    NOT NULL,
    status      TEXT    NOT NULL,
    message     TEXT,
    startedAt   BIGINT  NOT NULL,
    finishedAt  BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE CLIENT_SETTINGS_GLOBAL
(
    KEY                TEXT    NOT NULL PRIMARY KEY,
    VALUE              TEXT    NOT NULL,
    ALLOW_UNAUTHORIZED BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE CLIENT_SETTINGS_USER
(
    USER_ID TEXT NOT NULL,
    KEY     TEXT NOT NULL,
    VALUE   TEXT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID),
    PRIMARY KEY (KEY, USER_ID)
);

-- Indexes
CREATE INDEX idx__thumbnail_book__book_id ON THUMBNAIL_BOOK (BOOK_ID);
CREATE INDEX idx__book__series_id ON BOOK (SERIES_ID);
CREATE INDEX idx__book__library_id ON BOOK (LIBRARY_ID);
CREATE INDEX idx__book_metadata_author__book_id ON BOOK_METADATA_AUTHOR (BOOK_ID);
CREATE INDEX idx__book_metadata_tag__book_id ON BOOK_METADATA_TAG (BOOK_ID);
CREATE INDEX idx__media_file__book_id ON MEDIA_FILE (BOOK_ID);
CREATE INDEX idx__series__library_id ON SERIES (LIBRARY_ID);
CREATE INDEX idx__series_metadata_genre__series_id ON SERIES_METADATA_GENRE (SERIES_ID);
CREATE INDEX idx__series_metadata_tag__series_id ON SERIES_METADATA_TAG (SERIES_ID);
CREATE INDEX idx__book_metadata_aggregation_author__series_id ON BOOK_METADATA_AGGREGATION_AUTHOR (SERIES_ID);
CREATE INDEX idx__book__created_date ON BOOK (CREATED_DATE);
CREATE INDEX idx__book_metadata_link__book_id ON BOOK_METADATA_LINK (BOOK_ID);
CREATE INDEX idx__series_metadata_sharing__series_id ON SERIES_METADATA_SHARING (SERIES_ID);
CREATE INDEX idx__book_metadata_aggregation_tag__series_id ON BOOK_METADATA_AGGREGATION_TAG (SERIES_ID);
CREATE INDEX idx__thumbnail_collection__collection_id ON THUMBNAIL_COLLECTION (COLLECTION_ID);
CREATE INDEX idx__thumbnail_readlist__readlist_id ON THUMBNAIL_READLIST (READLIST_ID);
CREATE INDEX idx__thumbnail_series__series_id ON THUMBNAIL_SERIES (SERIES_ID);
CREATE INDEX idx__authentication_activity__user_id ON AUTHENTICATION_ACTIVITY (USER_ID);
CREATE INDEX idx__book_metadata__number_sort ON BOOK_METADATA (NUMBER_SORT);
CREATE INDEX idx__series__last_modified_date ON SERIES (LAST_MODIFIED_DATE);
CREATE INDEX idx__series__created_date ON SERIES (CREATED_DATE);
CREATE INDEX idx__book_metadata__release_date ON BOOK_METADATA (RELEASE_DATE);
CREATE INDEX idx__read_progress__last_modified_date ON READ_PROGRESS (LAST_MODIFIED_DATE);
CREATE INDEX idx__media__status ON MEDIA (STATUS);
CREATE INDEX idx__series_metadata_link__series_id ON SERIES_METADATA_LINK (SERIES_ID);
CREATE INDEX idx__series_metadata_alternate_title__series_id ON SERIES_METADATA_ALTERNATE_TITLE (SERIES_ID);
CREATE INDEX idx__series_metadata__title ON SERIES_METADATA (TITLE);
CREATE INDEX idx__library_exclusions__library_id ON LIBRARY_EXCLUSIONS (LIBRARY_ID);
CREATE INDEX idx__thumbnail_book__width ON THUMBNAIL_BOOK (WIDTH);
CREATE INDEX idx__thumbnail_book__height ON THUMBNAIL_BOOK (HEIGHT);
CREATE INDEX idx__thumbnail_book__file_size ON THUMBNAIL_BOOK (FILE_SIZE);
CREATE INDEX idx__user_api_key__user_id ON USER_API_KEY (USER_ID);
CREATE INDEX idx__sync_point__user_id ON SYNC_POINT (USER_ID);
CREATE INDEX idx__sync_point_book_removed_status__sync_point_id ON SYNC_POINT_BOOK_REMOVED_SYNCED (SYNC_POINT_ID);
CREATE INDEX idx__sync_point_book__sync_point_id ON SYNC_POINT_BOOK (SYNC_POINT_ID);
CREATE INDEX idx__sync_point_readlist__sync_point_id ON SYNC_POINT_READLIST (SYNC_POINT_ID);
CREATE INDEX idx__sync_point_readlist_book__sync_point_id_readlist_id ON SYNC_POINT_READLIST_BOOK (SYNC_POINT_ID, READLIST_ID);
CREATE INDEX book_thumbnails_series_idx ON BookThumbnail (seriesId);
CREATE INDEX book_thumbnails_server_type_idx ON BookThumbnail (mediaServer);
CREATE INDEX series_thumbnail_server_type_idx ON SeriesThumbnail (mediaServer);
CREATE INDEX series_match_type_idx ON SeriesMatch (type);
CREATE INDEX komf_job_series_id_idx ON KomfJobRecord(seriesId);
CREATE INDEX komf_job_status_idx ON KomfJobRecord(status);
CREATE INDEX komf_job_started_at_idx ON KomfJobRecord(startedAt);
CREATE INDEX komf_job_finished_at_idx ON KomfJobRecord(finishedAt);