-- Add columns to THUMBNAIL_BOOK
ALTER TABLE THUMBNAIL_BOOK
    ADD COLUMN WIDTH integer NOT NULL DEFAULT 0;
ALTER TABLE THUMBNAIL_BOOK
    ADD COLUMN HEIGHT integer NOT NULL DEFAULT 0;
ALTER TABLE THUMBNAIL_BOOK
    ADD COLUMN MEDIA_TYPE text NOT NULL DEFAULT '';
ALTER TABLE THUMBNAIL_BOOK
    ADD COLUMN FILE_SIZE bigint NOT NULL DEFAULT 0;

-- Add columns to THUMBNAIL_SERIES
ALTER TABLE THUMBNAIL_SERIES
    ADD COLUMN WIDTH integer NOT NULL DEFAULT 0;
ALTER TABLE THUMBNAIL_SERIES
    ADD COLUMN HEIGHT integer NOT NULL DEFAULT 0;
ALTER TABLE THUMBNAIL_SERIES
    ADD COLUMN MEDIA_TYPE text NOT NULL DEFAULT '';
ALTER TABLE THUMBNAIL_SERIES
    ADD COLUMN FILE_SIZE bigint NOT NULL DEFAULT 0;

-- Add columns to THUMBNAIL_COLLECTION
ALTER TABLE THUMBNAIL_COLLECTION
    ADD COLUMN WIDTH integer NOT NULL DEFAULT 0;
ALTER TABLE THUMBNAIL_COLLECTION
    ADD COLUMN HEIGHT integer NOT NULL DEFAULT 0;
ALTER TABLE THUMBNAIL_COLLECTION
    ADD COLUMN MEDIA_TYPE text NOT NULL DEFAULT '';
ALTER TABLE THUMBNAIL_COLLECTION
    ADD COLUMN FILE_SIZE bigint NOT NULL DEFAULT 0;

-- Add columns to THUMBNAIL_READLIST
ALTER TABLE THUMBNAIL_READLIST
    ADD COLUMN WIDTH integer NOT NULL DEFAULT 0;
ALTER TABLE THUMBNAIL_READLIST
    ADD COLUMN HEIGHT integer NOT NULL DEFAULT 0;
ALTER TABLE THUMBNAIL_READLIST
    ADD COLUMN MEDIA_TYPE text NOT NULL DEFAULT '';
ALTER TABLE THUMBNAIL_READLIST
    ADD COLUMN FILE_SIZE bigint NOT NULL DEFAULT 0;
