-- Recreate PAGE_HASH table
BEGIN;

-- Create new table structure
CREATE TABLE PAGE_HASH_NEW
(
    HASH               text      NOT NULL PRIMARY KEY,
    SIZE               bigint    NULL,
    ACTION             text      NOT NULL,
    DELETE_COUNT       integer   NOT NULL DEFAULT 0,
    CREATED_DATE       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Migrate data
INSERT INTO PAGE_HASH_NEW(HASH, ACTION, SIZE, DELETE_COUNT, CREATED_DATE, LAST_MODIFIED_DATE)
SELECT HASH, ACTION, SIZE, DELETE_COUNT, CREATED_DATE, LAST_MODIFIED_DATE
FROM PAGE_HASH;

-- Replace old table
DROP TABLE PAGE_HASH;
ALTER TABLE PAGE_HASH_NEW RENAME TO PAGE_HASH;

COMMIT;

-- Recreate PAGE_HASH_THUMBNAIL table
BEGIN;

-- Create new table structure
CREATE TABLE PAGE_HASH_THUMBNAIL_NEW
(
    HASH      text  NOT NULL PRIMARY KEY,
    THUMBNAIL bytea NOT NULL
);

-- Migrate data
INSERT INTO PAGE_HASH_THUMBNAIL_NEW(HASH, THUMBNAIL)
SELECT HASH, THUMBNAIL
FROM PAGE_HASH_THUMBNAIL;

-- Replace old table
DROP TABLE PAGE_HASH_THUMBNAIL;
ALTER TABLE PAGE_HASH_THUMBNAIL_NEW RENAME TO PAGE_HASH_THUMBNAIL;

COMMIT;
