ALTER TABLE BOOK
    ADD COLUMN FILE_HASH text NOT NULL DEFAULT '';

ALTER TABLE BOOK
    ADD COLUMN DELETED_DATE timestamp NULL DEFAULT NULL;

ALTER TABLE SERIES
    ADD COLUMN DELETED_DATE timestamp NULL DEFAULT NULL;

ALTER TABLE library
    ADD COLUMN EMPTY_TRASH_AFTER_SCAN boolean NOT NULL DEFAULT FALSE;
