CREATE TABLE SYNC_POINT_READLIST
(
    SYNC_POINT_ID               text      NOT NULL,
    READLIST_ID                 text      NOT NULL,
    READLIST_NAME               text      NOT NULL,
    READLIST_CREATED_DATE       timestamp NOT NULL,
    READLIST_LAST_MODIFIED_DATE timestamp NOT NULL,
    SYNCED                      boolean   NOT NULL DEFAULT FALSE,
    PRIMARY KEY (SYNC_POINT_ID, READLIST_ID),
    FOREIGN KEY (SYNC_POINT_ID) REFERENCES SYNC_POINT (ID)
);

CREATE INDEX IF NOT EXISTS idx__sync_point_readlist__sync_point_id ON SYNC_POINT_READLIST (SYNC_POINT_ID);

CREATE TABLE SYNC_POINT_READLIST_BOOK
(
    SYNC_POINT_ID text NOT NULL,
    READLIST_ID   text NOT NULL,
    BOOK_ID       text NOT NULL,
    PRIMARY KEY (SYNC_POINT_ID, READLIST_ID, BOOK_ID),
    FOREIGN KEY (SYNC_POINT_ID) REFERENCES SYNC_POINT (ID)
);

CREATE INDEX IF NOT EXISTS idx__sync_point_readlist_book__sync_point_id_readlist_id
    ON SYNC_POINT_READLIST_BOOK (SYNC_POINT_ID, READLIST_ID);

CREATE TABLE SYNC_POINT_READLIST_REMOVED_SYNCED
(
    SYNC_POINT_ID text NOT NULL,
    READLIST_ID   text NOT NULL,
    PRIMARY KEY (SYNC_POINT_ID, READLIST_ID),
    FOREIGN KEY (SYNC_POINT_ID) REFERENCES SYNC_POINT (ID)
);
