ALTER TABLE library
    ADD COLUMN IMPORT_BARCODE_ISBN boolean NOT NULL DEFAULT TRUE;

ALTER TABLE book_metadata
    ADD COLUMN ISBN text NOT NULL DEFAULT '';

ALTER TABLE book_metadata
    ADD COLUMN ISBN_LOCK boolean NOT NULL DEFAULT FALSE;
