CREATE TABLE USER_SHARING
(
    LABEL   text    NOT NULL,
    ALLOW   boolean NOT NULL,
    USER_ID text    NOT NULL,
    PRIMARY KEY (LABEL, ALLOW, USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES "user" (ID)
);

ALTER TABLE "user"
    ADD COLUMN AGE_RESTRICTION integer NULL;

ALTER TABLE "user"
    ADD COLUMN AGE_RESTRICTION_ALLOW_ONLY boolean NULL;

-- Add index for performance
CREATE INDEX idx__user_sharing__user_id ON USER_SHARING (USER_ID);
