CREATE TABLE USER_API_KEY
(
    ID                 text      NOT NULL PRIMARY KEY,
    USER_ID            text      NOT NULL,
    CREATED_DATE       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    API_KEY            text      NOT NULL UNIQUE,
    COMMENT            text      NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES "user" (ID)
);

CREATE INDEX IF NOT EXISTS idx__user_api_key__user_id ON USER_API_KEY (USER_ID);

ALTER TABLE AUTHENTICATION_ACTIVITY
    ADD COLUMN API_KEY_ID text NULL DEFAULT NULL;
ALTER TABLE AUTHENTICATION_ACTIVITY
    ADD COLUMN API_KEY_COMMENT text NULL DEFAULT NULL;
