UPDATE MEDIA
SET STATUS = 'OUTDATED'
WHERE BOOK_ID IN (
    SELECT M.BOOK_ID
    FROM MEDIA M
             LEFT JOIN MEDIA_PAGE MP ON M.BOOK_ID = MP.BOOK_ID
    GROUP BY M.BOOK_ID, M.PAGE_COUNT
    HAVING M.PAGE_COUNT <> COUNT(MP.BOOK_ID)
);
