-- PostgreSQL can add columns directly, but recreating for consistency
BEGIN;

-- Create new table structure
CREATE TABLE READ_PROGRESS_NEW
(
    BOOK_ID            text      NOT NULL,
    USER_ID            text      NOT NULL,
    CREATED_DATE       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PAGE               integer   NOT NULL,
    COMPLETED          boolean   NOT NULL,
    READ_DATE          timestamp NULL     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BOOK_ID, USER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID),
    FOREIGN KEY (USER_ID) REFERENCES "user" (ID)
);

-- Migrate data
INSERT INTO READ_PROGRESS_NEW(BOOK_ID, USER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PAGE, COMPLETED, READ_DATE)
SELECT BOOK_ID, USER_ID, CREATED_DATE, LAST_MODIFIED_DATE, PAGE, COMPLETED, LAST_MODIFIED_DATE
FROM READ_PROGRESS;

-- Replace old table
DROP TABLE READ_PROGRESS;
ALTER TABLE READ_PROGRESS_NEW RENAME TO READ_PROGRESS;

-- Recreate indexes
CREATE INDEX idx_read_progress_user_id ON READ_PROGRESS(USER_ID);
CREATE INDEX idx_read_progress_book_id ON READ_PROGRESS(BOOK_ID);

COMMIT;
