CREATE TABLE USER_ROLE
(
    USER_ID text NOT NULL,
    ROLE    text NOT NULL,
    PRIMARY KEY (USER_ID, ROLE),
    FOREIGN KEY (USER_ID) REFERENCES "user" (ID)
);

-- Migrate existing roles
INSERT INTO USER_ROLE
SELECT id, 'ADMIN'
FROM "user"
WHERE ROLE_ADMIN = TRUE;

INSERT INTO USER_ROLE
SELECT id, 'KOREADER_SYNC'
FROM "user"
WHERE ROLE_ADMIN = TRUE;

INSERT INTO USER_ROLE
SELECT id, 'FILE_DOWNLOAD'
FROM "user"
WHERE ROLE_FILE_DOWNLOAD = TRUE;

INSERT INTO USER_ROLE
SELECT id, 'PAGE_STREAMING'
FROM "user"
WHERE ROLE_PAGE_STREAMING = TRUE;

INSERT INTO USER_ROLE
SELECT id, 'KOBO_SYNC'
FROM "user"
WHERE ROLE_KOBO_SYNC = TRUE;

-- PostgreSQL can drop columns directly
ALTER TABLE "user" DROP COLUMN IF EXISTS ROLE_ADMIN;
ALTER TABLE "user" DROP COLUMN IF EXISTS ROLE_FILE_DOWNLOAD;
ALTER TABLE "user" DROP COLUMN IF EXISTS ROLE_PAGE_STREAMING;
ALTER TABLE "user" DROP COLUMN IF EXISTS ROLE_KOBO_SYNC;

-- Add index for performance
CREATE INDEX idx__user_role__user_id ON USER_ROLE (USER_ID);
