CREATE TABLE BOOK_METADATA_AGGREGATION_TAG
(
    TAG       text NOT NULL,
    SERIES_ID text NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

-- Aggregate existing data
INSERT INTO BOOK_METADATA_AGGREGATION_TAG
SELECT DISTINCT bt.TAG, b.SERIES_ID
FROM BOOK_METADATA_TAG bt
         LEFT JOIN BOOK B ON B.ID = bt.BOOK_ID;

-- Add index for performance
CREATE INDEX idx_book_metadata_aggregation_tag_series_id ON BOOK_METADATA_AGGREGATION_TAG(SERIES_ID);
CREATE INDEX idx_book_metadata_aggregation_tag_tag ON BOOK_METADATA_AGGREGATION_TAG(TAG);
