ALTER TABLE READ_PROGRESS_SERIES
    ADD COLUMN MOST_RECENT_READ_DATE timestamp NULL;
ALTER TABLE READ_PROGRESS_SERIES
    ADD COLUMN LAST_MODIFIED_DATE timestamp NULL;

UPDATE READ_PROGRESS_SERIES
SET MOST_RECENT_READ_DATE = (
    SELECT MAX(r.READ_DATE)
    FROM READ_PROGRESS r
             INNER JOIN BOOK b ON r.BOOK_ID = b.ID
    WHERE b.SERIES_ID = READ_PROGRESS_SERIES.SERIES_ID
);

UPDATE READ_PROGRESS_SERIES
SET LAST_MODIFIED_DATE = (
    SELECT MAX(r.LAST_MODIFIED_DATE)
    FROM READ_PROGRESS r
             INNER JOIN BOOK b ON r.BOOK_ID = b.ID
    WHERE b.SERIES_ID = READ_PROGRESS_SERIES.SERIES_ID
);
