UPDATE MEDIA
SET EXTENSION_VALUE = NULL;

UPDATE media
SET STATUS = 'OUTDATED'
WHERE MEDIA_TYPE = 'application/epub+zip'
  AND STATUS = 'READY';

ALTER TABLE MEDIA
    RENAME COLUMN EXTENSION_VALUE TO _UNUSED;

ALTER TABLE MEDIA
    ADD COLUMN EXTENSION_VALUE_BLOB bytea NULL;
