ALTER TABLE BOOK
    ADD COLUMN oneshot boolean NOT NULL DEFAULT FALSE;

ALTER TABLE SERIES
    ADD COLUMN oneshot boolean NOT NULL DEFAULT FALSE;

ALTER TABLE LIBRARY
    ADD COLUMN ONESHOTS_DIRECTORY text NULL DEFAULT NULL;
