ALTER TABLE SERIES
    ADD COLUMN BOOK_COUNT integer NOT NULL DEFAULT 0;

UPDATE SERIES
SET BOOK_COUNT = (
    SELECT COUNT(b.ID)
    FROM BOOK b
    WHERE b.SERIES_ID = SERIES.ID
);

CREATE TABLE READ_PROGRESS_SERIES
(
    SERIES_ID         text    NOT NULL,
    USER_ID           text    NOT NULL,
    READ_COUNT        integer NOT NULL,
    IN_PROGRESS_COUNT integer NOT NULL,
    PRIMARY KEY (SERIES_ID, USER_ID),
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID),
    FOREIGN KEY (USER_ID) REFERENCES "user" (ID)
);

INSERT INTO READ_PROGRESS_SERIES
SELECT BOOK.SERIES_ID,
       READ_PROGRESS.USER_ID,
       SUM(CASE WHEN READ_PROGRESS.COMPLETED = TRUE THEN 1 ELSE 0 END) as READ_COUNT,
       SUM(CASE WHEN READ_PROGRESS.COMPLETED = FALSE THEN 1 ELSE 0 END) as IN_PROGRESS_COUNT
FROM BOOK
         INNER JOIN READ_PROGRESS ON (BOOK.ID = READ_PROGRESS.BOOK_ID)
GROUP BY BOOK.SERIES_ID, READ_PROGRESS.USER_ID;

-- Add index for performance
CREATE INDEX idx_read_progress_series_user_id ON READ_PROGRESS_SERIES(USER_ID);
