-- Rename existing table
ALTER TABLE THUMBNAIL_SERIES RENAME TO TMP_THUMBNAIL_SERIES;

-- Create new table structure
CREATE TABLE THUMBNAIL_SERIES
(
    ID                  text      NOT NULL PRIMARY KEY,
    URL                 text      NULL DEFAULT NULL,
    SELECTED            boolean   NOT NULL DEFAULT FALSE,
    THUMBNAIL           bytea     NULL DEFAULT NULL,
    TYPE                text      NOT NULL,
    CREATED_DATE        timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    SERIES_ID           text      NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

-- Migrate data
INSERT INTO THUMBNAIL_SERIES(ID, URL, SELECTED, CREATED_DATE, LAST_MODIFIED_DATE, SERIES_ID, TYPE)
SELECT ID, URL, SELECTED, CREATED_DATE, LAST_MODIFIED_DATE, SERIES_ID, 'SIDECAR' AS TYPE
FROM TMP_THUMBNAIL_SERIES;

-- Drop temporary table
DROP TABLE TMP_THUMBNAIL_SERIES;

-- Recreate indexes
CREATE INDEX idx_thumbnail_series_series_id ON THUMBNAIL_SERIES(SERIES_ID);
CREATE INDEX idx_thumbnail_series_selected ON THUMBNAIL_SERIES(SERIES_ID, SELECTED);
