CREATE TABLE SERIES_METADATA_SHARING
(
    LABEL     text NOT NULL,
    SERIES_ID text NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

ALTER TABLE SERIES_METADATA
    ADD COLUMN SHARING_LABELS_LOCK boolean NOT NULL DEFAULT FALSE;

-- Add index for performance
CREATE INDEX idx__series_metadata_sharing__series_id ON SERIES_METADATA_SHARING (SERIES_ID);
