ALTER TABLE MEDIA_FILE
    ADD COLUMN MEDIA_TYPE text NULL;
ALTER TABLE MEDIA_FILE
    ADD COLUMN SUB_TYPE text NULL;
ALTER TABLE MEDIA_FILE
    ADD COLUMN FILE_SIZE bigint NULL;

ALTER TABLE MEDIA
    ADD COLUMN EXTENSION_CLASS text NULL;
ALTER TABLE MEDIA
    ADD COLUMN EXTENSION_VALUE text NULL;

UPDATE media
SET STATUS = 'OUTDATED'
WHERE MEDIA_TYPE = 'application/epub+zip'
  AND STATUS = 'READY';
