CREATE TABLE SERIES_METADATA_ALTERNATE_TITLE
(
    LABEL     text NOT NULL,
    TITLE     text NOT NULL,
    SERIES_ID text NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES (ID)
);

ALTER TABLE series_metadata
    ADD COLUMN ALTERNATE_TITLES_LOCK boolean NOT NULL DEFAULT FALSE;

CREATE INDEX idx__series_metadata_alternate_title__series_id
    ON SERIES_METADATA_ALTERNATE_TITLE (SERIES_ID);
