-- Clean up BOOK_METADATA_TAG
UPDATE BOOK_METADATA_TAG
SET TAG = lower(trim(TAG));

-- Remove duplicates from BOOK_METADATA_TAG
-- PostgreSQL approach using ctid (internal row identifier)
DELETE FROM BOOK_METADATA_TAG
WHERE ctid NOT IN (
    SELECT min(ctid)
    FROM BOOK_METADATA_TAG
    GROUP BY TAG, BOOK_ID
);

-- Clean up SERIES_METADATA_TAG
UPDATE SERIES_METADATA_TAG
SET TAG = lower(trim(TAG));

-- Remove duplicates from SERIES_METADATA_TAG
DELETE FROM SERIES_METADATA_TAG
WHERE ctid NOT IN (
    SELECT min(ctid)
    FROM SERIES_METADATA_TAG
    GROUP BY TAG, SERIES_ID
);

-- Clean up SERIES_METADATA_GENRE
UPDATE SERIES_METADATA_GENRE
SET GENRE = lower(trim(GENRE));

-- Remove duplicates from SERIES_METADATA_GENRE
DELETE FROM SERIES_METADATA_GENRE
WHERE ctid NOT IN (
    SELECT min(ctid)
    FROM SERIES_METADATA_GENRE
    GROUP BY GENRE, SERIES_ID
);
